[project]
name = "qfrsch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "pyarrow>=23.0.0",
    "wrds>=3.4.0",
]

[dependency-groups]
dev = [
    "pyarrow>=23.0.0",
    "wrds>=3.4.0",
]
